version: 1.0.0
services:
  tensorflow:
    container_name: ds-project-tensorflow
    image: ds-project-tensorflow:latest
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./out:/app/out:rw
      - ./neural-network.ipynb:/app/neural-network.ipynb:rw
    ports:
      - 8888:8888